### PR TITLE
LPS-108561 Replace convert-to-content-page-and-preview language key

### PR DESCRIPTION
**Pull request by amandaaakwok**
Ticket: https://issues.liferay.com/browse/LPS-108561

The layout drop down actions have been changed from "Convert to Content Page and Preview" to "Convert to Content Page ..."

### CODE REVIEW

**Comment by amandaaakwok** [comment]
ci:test:sf

**Comment by amandaaakwok** [comment]
ci:test:relevant

**Comment by amandaaakwok** [comment]
ci:stop

**Comment by amandaaakwok** [comment]
ci:stop

**Comment by amandaaakwok** [comment]
ci:stop

**Comment by amandaaakwok** [comment]
ci:test:sf

**Comment by amandaaakwok** [comment]
ci:test:relevant

**Comment by knchau** [comment]
Forwarded to: https://github.com/SamZiemer/liferay-portal/pull/730

**Pull request closed without merging**
